// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928173819_ConfirmacaoEmail")]
    partial class ConfirmacaoEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.RegistroGlicemia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("Dose")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<int?>("Glicemia")
                        .HasColumnType("int");

                    b.Property<bool>("GlicemiaAcimaDoLimite")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("Hora")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Data", "Hora")
                        .HasDatabaseName("IX_RegistrosGlicemia_UsuarioId_Data_Hora");

                    b.ToTable("RegistrosGlicemia", null, t =>
                        {
                            t.HasCheckConstraint("CK_Registros_Dose", "`Dose` BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Registros_GlicemiaFaixa", "`Glicemia` IS NULL OR `Glicemia` BETWEEN 20 AND 600");

                            t.HasCheckConstraint("CK_Registros_HI", "(`GlicemiaAcimaDoLimite` = 1 AND `Glicemia` IS NULL) OR (`GlicemiaAcimaDoLimite` = 0 AND `Glicemia` IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CodigoConfirmacaoExpiraEm")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodigoConfirmacaoHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CriadoEm")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DesativadoEm")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("FatorSensibilidade")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("HgtAlvo")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TentativasCodigo")
                        .HasColumnType("int");

                    b.Property<string>("TipoDiabetes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuarios_Email");

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_FatorSensibilidade", "`FatorSensibilidade` BETWEEN 1 AND 600");

                            t.HasCheckConstraint("CK_Usuarios_HgtAlvo", "`HgtAlvo` BETWEEN 1 AND 600");

                            t.HasCheckConstraint("CK_Usuarios_Idade", "`Idade` IS NULL OR `Idade` BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("Domain.Entities.RegistroGlicemia", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("RegistroGlicemia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RegistroGlicemia");
                });
#pragma warning restore 612, 618
        }
    }
}
